# Algebra Linear
A Álgebra Linear é o ramo da matemática que lida com espaços vetoriais.
Apesar de eu não achar que vou conseguir ensinar álgebra linear em um capítulo,
ela sustenta um grande número de conceitos e técnicas de data science, o que
significa que eu devo a você, ao menos, uma tentativa. O que aprenderemos
neste capítulo, usaremos excessivamente no decorrer do livro.

# Vetores
Concretamente (para nós), os vetores são pontos em algum espaço de dimensão
finita. Apesar de você não pensar em seus dados como vetores, eles são uma
ótima maneira de representar dados numéricos.

Por exemplo, se você tiver as alturas, pesos e idades de uma grande quantidade
de pessoas, pode tratar seus dados como vetores tridimensionais (height, weight,
age). Se você estiver ensinando uma turma com quatro testes, pode tratar as notas
dos alunos como vetores quadridimensionais (exam1, exam2, exam3, exam4).

A abordagem inicial mais simples é representar vetores como listas de números.
Uma lista de três números corresponde a um vetor em um espaço tridimensional,
e vice-versa:

In [2]:
height_weight_age = [70, 170, 40 ] # Polegadas_Kilos_anos
grades = [95,80,75,62 ] #testes 1,2,3,4

# Vetores em numpy
O tipo básico de dados é o ndarray que representa um array multidimensional.

In [12]:
import numpy as np
notas = np.array([7.8, 9.1, 8.6, 7.4])
type(notas)

numpy.ndarray

No Python representamos um vetor como um array do NumPy, então se temos apenas a informação da quantidade de m², temos um vetor com um eixo:

In [13]:
apto = np.array([67])

Adicionando a informação do valor do apartamento no vetor, teremos um vetor com dois eixos:

In [14]:
apto = np.array([67, 250])

Se continuarmos incluindo mais uma informação como a quantidade de quartos, teremos um vetor três eixos:

In [15]:
apto = np.array([67, 250, 2])

E podemos continuar adicionando informações no vetor e a cada novo valor aumentamos um eixo do vetor.

# Operações matematicas em vetores

In [29]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(f'Soma: {x.sum()}') # soma dos valores do vetor = 10
print(f'Valor minimo: {x.min()}') # menor valor do vetor = 1
print(f'Valor maximo: {x.max()}') # maior valor do vetor = 4
print(f'Potencia em vetor: {x**2}') #elevando vetor a uma potencia
print(f'Divisão em vetor: {x/2}') #dividindo vetor 
print(f'Raiz quadrada em um vetor: {x ** 0.5}') #raiz quadrada do vetor, elevando a 0.5

Soma: 10
Valor minimo: 1
Valor maximo: 4
Potencia em vetor: [ 1  4  9 16]
Divisão em vetor: [0.5 1.  1.5 2. ]
Raiz quadrada em um vetor: [1.         1.41421356 1.73205081 2.        ]


# Soma escalar
Também é possível fazer a soma escalar (com um número) no vetor, então um valor é somado a cada elemento do vetor. Exemplo, suponha um conjunto de média de notas dos alunos, e o professor bonzinho resolve dar 0.5 pontos para cada aluno:

In [32]:
notas = np.array([6.5, 8.0, 7.5, 4.5, 9.0, 6.5, 6.0, 5.5, 7.0, 8.0, 6.5, 7.5])
soma = notas + 0.5  #[7.0, 8.5, 8.0, 5.0, 9.5, 7.0, 6.5, 6.0, 7.5, 8.5, 7.0, 8.0]
soma

array([7. , 8.5, 8. , 5. , 9.5, 7. , 6.5, 6. , 7.5, 8.5, 7. , 8. ])

# Operações logicas do array no Numpy
Com o novo vetor de notas, queremos saber quais os alunos obtiveram nota maior ou igual a 7.0 e foram aprovados. Para isso, podemos aplicar uma comparação a cada elemento do vetor, exemplo:

In [34]:
aprovados = soma >= 7.0
aprovados
# o resultado é um vetor de booleanos: 
# array([True, True, True, False, True, True, False, False, True, True, True, True], dtype=bool) 
# que indica com True as notas que são maior ou igual a 7,0 e False as notas menores que 7,0.

array([ True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True])

In [35]:
soma[aprovados] #aplicando o filtro aprovados no vetor

array([7. , 8.5, 8. , 9.5, 7. , 7.5, 8.5, 7. , 8. ])

E contar quantos valores são True, portanto tem nota maior ou igual a 7,0:

In [37]:
qtdAprovados = sum(soma >= 7.0) 
qtdAprovados

9

# Multiplicação de vetores
Dois ou mais vetores podem ser multiplicados e para isso é calculado a multiplicação de cada elemento nas mesmas posições do vetor, exemplo:

In [39]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
mult = x * y  
mult

array([ 5, 12, 21, 32])

Se temos um vetor com as notas de um aluno:

E temos um vetor com o peso que representa cada uma das notas na disciplina:

Se multiplicarmos os dois vetores e somar seus valores, temos como resultado a nota que este aluno teve na disciplina:

In [41]:
notas = np.array([8.0, 7.0, 7.5, 9.5, 10.0])
pesos = np.array([0.2, 0.1, 0.1, 0.3, 0.3])
notaFinal = sum(notas * pesos)
print(notas*pesos) #cada nota com peso aplicado
notaFinal

[1.6  0.7  0.75 2.85 3.  ]


8.9

# Multiplicação de escalar
Também é possível fazer a multiplicação escalar (com um número) no vetor, então um valor é multiplicado a cada elemento do vetor. Exemplo, suponha que temos um vetor os valores pagos com comida em um restaurante:

In [43]:
valores = np.array([18.0, 16.5, 17.0, 19.5, 18.5])

E queremos calcular 10% de gorjeta para cada um dos valores:

In [47]:
gorjeta = valores * 0.1  
print(gorjeta)
print(f'Total da gorjeta: {sum(gorjeta)}')

[1.8  1.65 1.7  1.95 1.85]
Total da gorjeta: 8.950000000000001


# Produto escalar de vetores
Equação do produto escalar de dois vetores
![Equação do produto escalar de dois vetores.](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-02.png)

sendo x e y, dois vetores de tamanho iguais e n o tamanho dos vetores, o produto escalar é a somatória da multiplicação de dois vetores, exemplo:

In [48]:
#mutiplica os dois vetores depois efetua a soma dos valores
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
prod = np.dot(x, y)
prod

70

Para calcular a soma dos quadrados de um vetor, também podemos usar o produto escalar.

Equação dos quadrados de um vetor
![Equação dos quadrados de umvetor](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-03.png)

In [61]:
x = np.array([1, 2, 3, 4])
np.dot(x, x)# mutiplicando o vetor por ele mesmo, elevando ao quadrado e somando os valores o mesmo que: sum(x ** 2)


30

# Distância entre vetores
Na imagem temos o vetor [1,4] (quadrado verde) e um vetor [2,1] (quadrado azul). Temos um novo vetor [4,2] (triângulo vermelho), mas gostaríamos de classificar este novo vetor como quadrado verde ou azul. Para isso podemos verificar qual o quadrado mais próximo e usar a mesma cor, mas qual quadrado está mais perto do triângulo?

![](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-04.png)

Na Figura 5 podemos perceber que o quadrado azul está mais próximo do triângulo vermelho, então podemos classificar este novo vetor como um quadrado azul.

![](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-05.png)

Uma das formas de calcular a distância entre vetores é usando a Distância Euclidiana, que é dada pela equação:

![](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-06.png)

Então,  calculamos o distância euclidiana entre o vetor [1,4] (quadrado verde) com o vetor [4,2] (triângulo vermelho).

![](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-07.png)

E  calculamos distância euclidiana entre o vetor [2,1] (quadrado azul) com o vetor [4,2] (triângulo vermelho).

![](http://www.sakurai.dev.br/images/posts/2019-06-21-revisao-algebra-linear-python-08.png)

Portanto, sabemos que a menor distância é em relação ao quadrado azul.

Usando o Python, podemos calcular a distância entre os vetores:

In [65]:
qv = np.array([1,4])    # Quadrado verde
qa = np.array([2,1])    # Quadrado azul
tv = np.array([4,2])    # Triângulo vermelho

distanciaQuadradoVerde = np.sqrt(sum((qv - tv) ** 2)) #3.6055
distanciaQuadradoAzul  = np.sqrt(sum((qa - tv) ** 2)) #2.2360
print(f'Distania do quadrado Verde: {distanciaQuadradoVerde}')
print(f'Distancia do quadrado azul: {distanciaQuadradoAzul}')

Distania do quadrado Verde: 3.605551275463989
Distancia do quadrado azul: 2.23606797749979


# Matrizes
Matriz é formada por um conjunto de vetores, normalmente representada em maiúsculo, como A[m, n] que tem m linhas por n colunas. O Numpy tem o objeto matrix que representa uma matriz, exemplo:

In [67]:
A = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8]])
A

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Nesse caso dizemos que a matriz A tem tamanho [2, 4], ou duas linhas e quatro colunas. Para acessar uma determinada posição da matriz precisamos informar os valores da linha e coluna, lembrando que os índices começam com zero, o valor da posição A[1, 3] é 8.

# Soma de matrizes

In [69]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])

SOMA = A + B
SOMA

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

# Transposta
Com o Numpy podemos obter facilmente a transposta de uma matriz:

In [71]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
A.T 

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

# Multiplicação de matrizes
Para multiplicar duas matrizes é necessário que uma matriz A tenha dimensão m x n enquanto que a matriz B tenha a dimensão n x m, como resultado temos uma matriz de dimensão m x m.

In [92]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2],
               [3, 4], 
               [5, 6],
               [7, 8]])
mult = A * B
mult

matrix([[ 50,  60],
        [114, 140]])